// Package openai provides types and utilities for OpenAI API compatibility.
// These types match the OpenAI API specification to ensure drop-in compatibility
// with any OpenAI SDK client.
package openai

import (
	"bytes"
	"encoding/json"
	"strings"
	"time"
)

// ChatCompletionRequest represents a request to the /v1/chat/completions endpoint.
type ChatCompletionRequest struct {
	// Model is the ID of the model to use. Use "auto" for automatic routing.
	Model string `json:"model"`

	// Messages is a list of messages comprising the conversation so far.
	Messages []ChatMessage `json:"messages"`

	// Temperature controls randomness. Lower values make responses more deterministic.
	// Range: 0.0 to 2.0. Default: 1.0
	Temperature *float64 `json:"temperature,omitempty"`

	// TopP is an alternative to temperature for nucleus sampling.
	// Range: 0.0 to 1.0. Default: 1.0
	TopP *float64 `json:"top_p,omitempty"`

	// N is the number of chat completion choices to generate.
	// Default: 1
	N *int `json:"n,omitempty"`

	// Stream enables server-sent events for streaming responses.
	// Default: false
	Stream bool `json:"stream,omitempty"`

	// Stop sequences where the API will stop generating further tokens.
	Stop []string `json:"stop,omitempty"`

	// MaxTokens is the maximum number of tokens to generate.
	MaxTokens *int `json:"max_tokens,omitempty"`

	// PresencePenalty penalizes new tokens based on whether they appear in the text so far.
	// Range: -2.0 to 2.0. Default: 0
	PresencePenalty *float64 `json:"presence_penalty,omitempty"`

	// FrequencyPenalty penalizes new tokens based on their existing frequency.
	// Range: -2.0 to 2.0. Default: 0
	FrequencyPenalty *float64 `json:"frequency_penalty,omitempty"`

	// LogitBias modifies the likelihood of specified tokens appearing.
	LogitBias map[string]float64 `json:"logit_bias,omitempty"`

	// User is a unique identifier representing your end-user.
	User string `json:"user,omitempty"`

	// ResponseFormat specifies the format of the response.
	ResponseFormat *ResponseFormat `json:"response_format,omitempty"`

	// Seed for deterministic sampling (beta).
	Seed *int `json:"seed,omitempty"`

	// Tools is a list of tools the model may call.
	Tools []Tool `json:"tools,omitempty"`

	// ToolChoice controls which tool is called by the model.
	ToolChoice interface{} `json:"tool_choice,omitempty"`
}

// ChatMessage represents a single message in a chat conversation.
type ChatMessage struct {
	// Role is the role of the message author: "system", "user", "assistant", or "tool".
	Role string `json:"role"`

	// Content is the contents of the message.
	Content string `json:"content"`

	// Name is an optional name for the participant (for multi-user chats).
	Name string `json:"name,omitempty"`

	// ToolCalls is the tool calls generated by the model.
	ToolCalls []ToolCall `json:"tool_calls,omitempty"`

	// ToolCallID is the ID of the tool call this message is responding to.
	ToolCallID string `json:"tool_call_id,omitempty"`
}

// UnmarshalJSON decodes a chat message, accepting the OpenAI `content` field in
// either of its two valid shapes: a plain string, or an array of content parts
// (e.g. [{"type":"text","text":"..."}, {"type":"image_url", ...}]). Text parts
// are concatenated (joined with newlines); non-text parts (such as image_url)
// are skipped because the backend models are text-only. This keeps the public
// Content field a flat string so all downstream consumers are unaffected.
func (m *ChatMessage) UnmarshalJSON(data []byte) error {
	// Alias avoids infinite recursion; Content captured raw for custom handling.
	type alias ChatMessage
	aux := &struct {
		Content json.RawMessage `json:"content"`
		*alias
	}{alias: (*alias)(m)}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	m.Content = flattenContent(aux.Content)
	return nil
}

// flattenContent converts the raw JSON of an OpenAI message `content` field into
// a plain string. It accepts a JSON string, a JSON array of content parts, or
// null/absent (which yields an empty string).
func flattenContent(raw json.RawMessage) string {
	trimmed := bytes.TrimSpace(raw)
	if len(trimmed) == 0 || string(trimmed) == "null" {
		return ""
	}

	// Plain string content.
	if trimmed[0] == '"' {
		var s string
		if err := json.Unmarshal(trimmed, &s); err == nil {
			return s
		}
		return ""
	}

	// Array of content parts.
	if trimmed[0] == '[' {
		var parts []struct {
			Type string `json:"type"`
			Text string `json:"text"`
		}
		if err := json.Unmarshal(trimmed, &parts); err != nil {
			return ""
		}
		var texts []string
		for _, p := range parts {
			// Collect text parts; skip images and other non-text modalities.
			if p.Text != "" && (p.Type == "" || p.Type == "text") {
				texts = append(texts, p.Text)
			}
		}
		return strings.Join(texts, "\n")
	}

	return ""
}

// ChatCompletionResponse represents the response from /v1/chat/completions.
type ChatCompletionResponse struct {
	// ID is a unique identifier for this completion.
	ID string `json:"id"`

	// Object is always "chat.completion".
	Object string `json:"object"`

	// Created is the Unix timestamp of when the completion was created.
	Created int64 `json:"created"`

	// Model is the model used for the completion.
	Model string `json:"model"`

	// Choices is a list of chat completion choices.
	Choices []ChatCompletionChoice `json:"choices"`

	// Usage contains token usage information.
	Usage *Usage `json:"usage,omitempty"`

	// SystemFingerprint is a fingerprint of the system configuration.
	SystemFingerprint string `json:"system_fingerprint,omitempty"`
}

// ChatCompletionChoice represents a single completion choice.
type ChatCompletionChoice struct {
	// Index is the index of this choice in the list.
	Index int `json:"index"`

	// Message is the chat message generated by the model.
	Message ChatMessage `json:"message"`

	// FinishReason indicates why the model stopped generating tokens.
	// Values: "stop", "length", "tool_calls", "content_filter", or null.
	FinishReason *string `json:"finish_reason"`

	// LogProbs contains log probability information (if requested).
	LogProbs *LogProbs `json:"logprobs,omitempty"`
}

// ChatChoice is an alias for server compatibility (non-pointer finish reason).
type ChatChoice struct {
	Index        int         `json:"index"`
	Message      ChatMessage `json:"message"`
	FinishReason string      `json:"finish_reason"`
}

// ChatChunkChoice is a streaming chunk choice with non-pointer finish reason.
type ChatChunkChoice struct {
	Index        int       `json:"index"`
	Delta        ChatDelta `json:"delta"`
	FinishReason string    `json:"finish_reason,omitempty"`
}

// ChatDelta represents delta content in streaming.
type ChatDelta struct {
	Role    string `json:"role,omitempty"`
	Content string `json:"content,omitempty"`
}

// ChatCompletionChunk represents a single chunk in a streaming response.
type ChatCompletionChunk struct {
	// ID is a unique identifier for this completion.
	ID string `json:"id"`

	// Object is always "chat.completion.chunk".
	Object string `json:"object"`

	// Created is the Unix timestamp of when the chunk was created.
	Created int64 `json:"created"`

	// Model is the model used for the completion.
	Model string `json:"model"`

	// Choices contains the streamed choices.
	Choices []ChatCompletionChunkChoice `json:"choices"`

	// SystemFingerprint is a fingerprint of the system configuration.
	SystemFingerprint string `json:"system_fingerprint,omitempty"`
}

// ChatCompletionChunkChoice represents a single choice in a streaming chunk.
type ChatCompletionChunkChoice struct {
	// Index is the index of this choice.
	Index int `json:"index"`

	// Delta contains the streamed message delta.
	Delta ChatMessageDelta `json:"delta"`

	// FinishReason indicates why the model stopped (only in final chunk).
	FinishReason *string `json:"finish_reason"`

	// LogProbs contains log probability information (if requested).
	LogProbs *LogProbs `json:"logprobs,omitempty"`
}

// ChatMessageDelta represents the delta content in a streaming chunk.
type ChatMessageDelta struct {
	// Role is only present in the first chunk.
	Role string `json:"role,omitempty"`

	// Content is the delta content.
	Content string `json:"content,omitempty"`

	// ToolCalls are the delta tool calls.
	ToolCalls []ToolCallDelta `json:"tool_calls,omitempty"`
}

// Usage contains token usage information.
type Usage struct {
	// PromptTokens is the number of tokens in the prompt.
	PromptTokens int `json:"prompt_tokens"`

	// CompletionTokens is the number of tokens in the completion.
	CompletionTokens int `json:"completion_tokens"`

	// TotalTokens is the total number of tokens used.
	TotalTokens int `json:"total_tokens"`
}

// ResponseFormat specifies the format of the response.
type ResponseFormat struct {
	// Type is the response format type: "text" or "json_object".
	Type string `json:"type"`
}

// Tool represents a tool that the model may call.
type Tool struct {
	// Type is the type of tool (currently only "function").
	Type string `json:"type"`

	// Function contains the function definition.
	Function ToolFunction `json:"function"`
}

// ToolFunction describes a function that can be called.
type ToolFunction struct {
	// Name is the name of the function.
	Name string `json:"name"`

	// Description describes what the function does.
	Description string `json:"description,omitempty"`

	// Parameters is a JSON Schema object describing the function parameters.
	Parameters json.RawMessage `json:"parameters,omitempty"`
}

// ToolCall represents a tool call made by the model.
type ToolCall struct {
	// ID is the ID of the tool call.
	ID string `json:"id"`

	// Type is the type of tool call (currently only "function").
	Type string `json:"type"`

	// Function contains the function call details.
	Function ToolCallFunction `json:"function"`
}

// ToolCallFunction contains the details of a function call.
type ToolCallFunction struct {
	// Name is the name of the function to call.
	Name string `json:"name"`

	// Arguments is a JSON string of arguments to call the function with.
	Arguments string `json:"arguments"`
}

// ToolCallDelta represents a delta tool call in streaming.
type ToolCallDelta struct {
	// Index is the index of this tool call.
	Index int `json:"index"`

	// ID is the ID of the tool call (only in first chunk).
	ID string `json:"id,omitempty"`

	// Type is the type of tool call (only in first chunk).
	Type string `json:"type,omitempty"`

	// Function contains the delta function call.
	Function *ToolCallFunctionDelta `json:"function,omitempty"`
}

// ToolCallFunctionDelta contains delta function call details.
type ToolCallFunctionDelta struct {
	// Name is the function name (only in first chunk).
	Name string `json:"name,omitempty"`

	// Arguments is a delta of the arguments string.
	Arguments string `json:"arguments,omitempty"`
}

// LogProbs contains log probability information.
type LogProbs struct {
	// Content contains token log probabilities.
	Content []TokenLogProb `json:"content,omitempty"`
}

// TokenLogProb contains log probability for a single token.
type TokenLogProb struct {
	// Token is the token string.
	Token string `json:"token"`

	// LogProb is the log probability of this token.
	LogProb float64 `json:"logprob"`

	// Bytes is the UTF-8 bytes of the token.
	Bytes []int `json:"bytes,omitempty"`

	// TopLogProbs contains the most likely tokens.
	TopLogProbs []TopLogProb `json:"top_logprobs,omitempty"`
}

// TopLogProb contains a top log probability entry.
type TopLogProb struct {
	// Token is the token string.
	Token string `json:"token"`

	// LogProb is the log probability.
	LogProb float64 `json:"logprob"`

	// Bytes is the UTF-8 bytes of the token.
	Bytes []int `json:"bytes,omitempty"`
}

// CompletionRequest represents a request to the /v1/completions endpoint (legacy).
type CompletionRequest struct {
	// Model is the ID of the model to use.
	Model string `json:"model"`

	// Prompt is the prompt to generate completions for.
	Prompt string `json:"prompt"`

	// MaxTokens is the maximum number of tokens to generate.
	MaxTokens *int `json:"max_tokens,omitempty"`

	// Temperature controls randomness.
	Temperature *float64 `json:"temperature,omitempty"`

	// TopP is for nucleus sampling.
	TopP *float64 `json:"top_p,omitempty"`

	// N is the number of completions to generate.
	N *int `json:"n,omitempty"`

	// Stream enables streaming.
	Stream bool `json:"stream,omitempty"`

	// LogProbs returns log probabilities.
	LogProbs *int `json:"logprobs,omitempty"`

	// Echo echoes back the prompt.
	Echo bool `json:"echo,omitempty"`

	// Stop sequences.
	Stop []string `json:"stop,omitempty"`

	// PresencePenalty penalizes presence.
	PresencePenalty *float64 `json:"presence_penalty,omitempty"`

	// FrequencyPenalty penalizes frequency.
	FrequencyPenalty *float64 `json:"frequency_penalty,omitempty"`

	// BestOf generates multiple completions server-side.
	BestOf *int `json:"best_of,omitempty"`

	// LogitBias modifies token likelihood.
	LogitBias map[string]float64 `json:"logit_bias,omitempty"`

	// User is the end-user identifier.
	User string `json:"user,omitempty"`

	// Suffix comes after the completion.
	Suffix string `json:"suffix,omitempty"`

	// Seed for deterministic sampling.
	Seed *int `json:"seed,omitempty"`
}

// CompletionResponse represents the response from /v1/completions.
type CompletionResponse struct {
	// ID is a unique identifier.
	ID string `json:"id"`

	// Object is always "text_completion".
	Object string `json:"object"`

	// Created is the Unix timestamp.
	Created int64 `json:"created"`

	// Model is the model used.
	Model string `json:"model"`

	// Choices contains the completion choices.
	Choices []CompletionChoice `json:"choices"`

	// Usage contains token usage.
	Usage *Usage `json:"usage,omitempty"`

	// SystemFingerprint is the system fingerprint.
	SystemFingerprint string `json:"system_fingerprint,omitempty"`
}

// CompletionChoice represents a single completion choice.
type CompletionChoice struct {
	// Text is the generated text.
	Text string `json:"text"`

	// Index is the choice index.
	Index int `json:"index"`

	// LogProbs contains log probabilities.
	LogProbs *CompletionLogProbs `json:"logprobs,omitempty"`

	// FinishReason indicates why generation stopped.
	FinishReason string `json:"finish_reason"`
}

// CompletionLogProbs contains log probability information for completions.
type CompletionLogProbs struct {
	// Tokens is the list of tokens.
	Tokens []string `json:"tokens,omitempty"`

	// TokenLogProbs is the log probabilities.
	TokenLogProbs []float64 `json:"token_logprobs,omitempty"`

	// TopLogProbs contains top alternatives.
	TopLogProbs []map[string]float64 `json:"top_logprobs,omitempty"`

	// TextOffset is the character offset.
	TextOffset []int `json:"text_offset,omitempty"`
}

// EmbeddingRequest represents a request to /v1/embeddings.
type EmbeddingRequest struct {
	// Input is the text(s) to embed.
	Input interface{} `json:"input"`

	// Model is the embedding model to use.
	Model string `json:"model"`

	// EncodingFormat is the encoding format ("float" or "base64").
	EncodingFormat string `json:"encoding_format,omitempty"`

	// User is the end-user identifier.
	User string `json:"user,omitempty"`

	// Dimensions is the desired embedding dimensions (for supported models).
	Dimensions *int `json:"dimensions,omitempty"`
}

// EmbeddingResponse represents the response from /v1/embeddings.
type EmbeddingResponse struct {
	// Object is always "list".
	Object string `json:"object"`

	// Data contains the embedding vectors.
	Data []Embedding `json:"data"`

	// Model is the model used.
	Model string `json:"model"`

	// Usage contains token usage.
	Usage EmbeddingUsage `json:"usage"`
}

// Embedding represents a single embedding vector.
type Embedding struct {
	// Object is always "embedding".
	Object string `json:"object"`

	// Embedding is the embedding vector.
	Embedding []float64 `json:"embedding"`

	// Index is the index in the input list.
	Index int `json:"index"`
}

// EmbeddingData is an alias with float32 for server compatibility.
type EmbeddingData struct {
	Object    string    `json:"object"`
	Index     int       `json:"index"`
	Embedding []float32 `json:"embedding"`
}

// ModelList represents the response from /v1/models.
type ModelList struct {
	Object string  `json:"object"`
	Data   []Model `json:"data"`
}

// EmbeddingUsage contains token usage for embeddings.
type EmbeddingUsage struct {
	// PromptTokens is the number of tokens.
	PromptTokens int `json:"prompt_tokens"`

	// TotalTokens is the total tokens.
	TotalTokens int `json:"total_tokens"`
}

// ModelsResponse represents the response from /v1/models.
type ModelsResponse struct {
	// Object is always "list".
	Object string `json:"object"`

	// Data contains the list of models.
	Data []Model `json:"data"`
}

// Model represents a single model.
type Model struct {
	// ID is the model identifier.
	ID string `json:"id"`

	// Object is always "model".
	Object string `json:"object"`

	// Created is the Unix timestamp when the model was created.
	Created int64 `json:"created"`

	// OwnedBy is the organization that owns the model.
	OwnedBy string `json:"owned_by"`
}

// NewChatCompletionResponse creates a new ChatCompletionResponse.
func NewChatCompletionResponse(id, model string, message ChatMessage, finishReason string, usage *Usage) *ChatCompletionResponse {
	reason := finishReason
	return &ChatCompletionResponse{
		ID:      id,
		Object:  "chat.completion",
		Created: time.Now().Unix(),
		Model:   model,
		Choices: []ChatCompletionChoice{
			{
				Index:        0,
				Message:      message,
				FinishReason: &reason,
			},
		},
		Usage: usage,
	}
}

// NewChatCompletionChunk creates a new streaming chunk.
func NewChatCompletionChunk(id, model string, delta ChatMessageDelta, finishReason *string) *ChatCompletionChunk {
	return &ChatCompletionChunk{
		ID:      id,
		Object:  "chat.completion.chunk",
		Created: time.Now().Unix(),
		Model:   model,
		Choices: []ChatCompletionChunkChoice{
			{
				Index:        0,
				Delta:        delta,
				FinishReason: finishReason,
			},
		},
	}
}
